# Generated by Django 5.2.10 on 2026-01-25 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Commercial name of the company', max_length=255, verbose_name='Company Name')),
                ('legal_name', models.CharField(help_text='Official registered legal name', max_length=255, verbose_name='Legal Name')),
                ('abbreviation', models.CharField(help_text='5-character uppercase code for matricule generation', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Abbreviation must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')], verbose_name='Abbreviation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Company Logo')),
                ('matricule_fiscale', models.CharField(blank=True, default='', help_text='Tax identification number', max_length=50, verbose_name='Matricule Fiscale')),
                ('registre_commerce', models.CharField(blank=True, default='', help_text='Commercial register number', max_length=50, verbose_name='Registre de Commerce')),
                ('activity_code', models.CharField(blank=True, default='', help_text='NAF/APE activity classification code', max_length=20, verbose_name='Activity Code')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name')),
                ('rib', models.CharField(blank=True, default='', help_text='20-digit bank account identifier', max_length=20, validators=[django.core.validators.RegexValidator(message='RIB must contain up to 20 digits only', regex='^\\d{0,20}$')], verbose_name='RIB')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this company is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
    ]
