# Generated by Django 5.2.11 on 2026-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Auto-generated from company name (max 5 chars, uppercase)', max_length=5, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Official registered legal name (auto-filled from name if empty)', max_length=255, verbose_name='Legal Name'),
        ),
    ]
