# Generated by Django 5.2.11 on 2026-02-23 20:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the store/warehouse', max_length=255, verbose_name='Store Name')),
                ('code', models.CharField(help_text='Unique code for the store (e.g., WH001, STR-TUN)', max_length=20, verbose_name='Store Code')),
                ('store_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('RETAIL', 'Retail Store'), ('DISTRIBUTION', 'Distribution Center')], default='WAREHOUSE', max_length=20, verbose_name='Store Type')),
                ('address', models.TextField(blank=True, default='', help_text='Full address of the store', verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this store is active', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Default store for new inventory', verbose_name='Default Store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='The company that owns this store', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'store',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Unique movement reference (auto-generated)', max_length=50, unique=True, verbose_name='Reference Number')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase/Receipt'), ('RETURN_IN', 'Customer Return'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment (Add)'), ('INITIAL', 'Initial Stock'), ('SALE', 'Sale'), ('RETURN_OUT', 'Return to Supplier'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_OUT', 'Adjustment (Remove)'), ('DAMAGE', 'Damaged/Expired')], max_length=20, verbose_name='Movement Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('quantity', models.IntegerField(help_text='Quantity moved (always positive)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('quantity_before', models.IntegerField(help_text='Stock level before this movement', verbose_name='Quantity Before')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this movement', verbose_name='Quantity After')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this movement', max_digits=12, null=True, verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of this movement', max_digits=14, null=True, verbose_name='Total Cost')),
                ('external_reference', models.CharField(blank=True, default='', help_text='Order ID, Invoice Number, etc.', max_length=100, verbose_name='External Reference')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this movement', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product', verbose_name='Product')),
                ('related_movement', models.OneToOneField(blank=True, help_text='The paired movement for transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_movement', to='inventory.inventorymovement', verbose_name='Related Movement')),
                ('destination_store', models.ForeignKey(blank=True, help_text='For transfers: destination store', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.store', verbose_name='Destination Store')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity in this store', verbose_name='Quantity')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved for pending orders', verbose_name='Reserved Quantity')),
                ('minimum_quantity', models.IntegerField(default=0, help_text='Reorder point - alert when quantity falls below this', verbose_name='Minimum Quantity')),
                ('maximum_quantity', models.IntegerField(blank=True, help_text='Maximum stock capacity for this store', null=True, verbose_name='Maximum Quantity')),
                ('bin_location', models.CharField(blank=True, default='', help_text='Shelf/bin location within the store (e.g., A1-B2)', max_length=50, verbose_name='Bin Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='Date of last physical inventory count', null=True, verbose_name='Last Physical Count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='products.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Inventory',
                'verbose_name_plural': 'Store Inventories',
                'db_table': 'store_inventory',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['company', 'is_active'], name='store_company_4d2bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['code'], name='store_code_91ed9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_number'], name='inventory_m_referen_2707ed_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['store', 'product'], name='inventory_m_store_i_eff802_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='inventory_m_movemen_6d66c7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['status'], name='inventory_m_status_0e35b5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inventory_m_created_b65c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['store', 'product'], name='store_inven_store_i_a52619_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['product'], name='store_inven_product_e52cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['quantity'], name='store_inven_quantit_b2e00a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
    ]
