# Generated by Django 5.2.11 on 2026-02-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consolidate_store_to_saleschannel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_m_referen_2707ed_idx',
            old_name='inv_mov_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_m_sales_c_612ff8_idx',
            old_name='inv_mov_channel_product_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_m_movemen_6d66c7_idx',
            old_name='inv_mov_type_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_m_status_0e35b5_idx',
            old_name='inv_mov_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_m_created_b65c6f_idx',
            old_name='inv_mov_created_idx',
        ),
        migrations.RenameIndex(
            model_name='saleschannelinventory',
            new_name='store_inven_sales_c_035ecf_idx',
            old_name='store_inven_sales_c_idx',
        ),
        migrations.RenameIndex(
            model_name='saleschannelinventory',
            new_name='store_inven_product_e52cd7_idx',
            old_name='store_inven_product_idx',
        ),
        migrations.RenameIndex(
            model_name='saleschannelinventory',
            new_name='store_inven_quantit_b2e00a_idx',
            old_name='store_inven_qty_idx',
        ),
    ]
