# Generated by Django 5.2.13 on 2026-05-28 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bom_production_batches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billofmaterials',
            new_name='bill_of_mat_finishe_f97e08_idx',
            old_name='bill_of_mat_finishe_2cfd0f_idx',
        ),
        migrations.RenameIndex(
            model_name='billofmaterials',
            new_name='bill_of_mat_is_acti_04a066_idx',
            old_name='bill_of_mat_is_acti_dfb79d_idx',
        ),
        migrations.RenameIndex(
            model_name='billofmaterialsitem',
            new_name='bill_of_mat_bom_id_7e9d82_idx',
            old_name='bill_of_mat_bom_id_71d7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='billofmaterialsitem',
            new_name='bill_of_mat_compone_1d6f63_idx',
            old_name='bill_of_mat_compone_3803bb_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='production__sales_c_7d93be_idx',
            old_name='production__sales__2b8179_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='production__status_9fdff2_idx',
            old_name='production__status_6db930_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='production__created_a85f07_idx',
            old_name='production__created_8f27d0_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatchcomponent',
            new_name='production__product_5e2cdf_idx',
            old_name='production__product_09a72c_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatchcomponent',
            new_name='production__compone_c986fb_idx',
            old_name='production__compone_4fd201_idx',
        ),
        migrations.AlterField(
            model_name='billofmaterialsitem',
            name='waste_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional expected waste percentage added when sending to factory.', max_digits=5),
        ),
    ]
