# Generated by Django 5.2.13 on 2026-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_bill_of_mat_finishe_2cfd0f_idx_bill_of_mat_finishe_f97e08_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase/Receipt'), ('RETURN_IN', 'Customer Return'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment (Add)'), ('INITIAL', 'Initial Stock'), ('SALE', 'Sale'), ('RETURN_OUT', 'Return to Supplier'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT_OUT', 'Adjustment (Remove)'), ('DAMAGE', 'Damaged/Expired'), ('SENT_TO_FACTORY', 'Sent to Factory'), ('PRODUCTION_IN', 'Production Receipt'), ('RESERVATION', 'Stock Reserved'), ('RELEASE', 'Reservation Released')], max_length=20, verbose_name='Movement Type'),
        ),
    ]
