# Generated by Django 5.2.10 on 2026-01-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('channel_type', models.CharField(choices=[('WOOCOMMERCE', 'WooCommerce'), ('POS', 'Point of Sale')], max_length=20, verbose_name='Channel Type')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this sales channel is active', verbose_name='Active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Flexible JSON config for API keys, warehouse IDs, etc.', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='brands.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Sales Channel',
                'verbose_name_plural': 'Sales Channels',
                'db_table': 'sales_channel',
                'ordering': ['brand', 'name'],
            },
        ),
    ]
