# Generated by Django 5.2.10 on 2026-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannel',
            name='config',
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='woocommerce_config',
            field=models.JSONField(blank=True, default=dict, help_text='WooCommerce API credentials: consumer_key, consumer_secret, webhook_token, store_url', verbose_name='WooCommerce Configuration'),
        ),
    ]
