# Generated by Django 5.2.12 on 2026-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0003_add_store_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleschannel',
            name='woocommerce_config',
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='wc_consumer_key',
            field=models.CharField(blank=True, default='', help_text='WooCommerce REST API consumer key', max_length=255, verbose_name='Consumer Key'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='wc_consumer_secret',
            field=models.CharField(blank=True, default='', help_text='WooCommerce REST API consumer secret', max_length=255, verbose_name='Consumer Secret'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='wc_store_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://example.com', max_length=500, verbose_name='WooCommerce Store URL'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='wc_webhook_token',
            field=models.CharField(blank=True, default='', help_text='Token for authenticating incoming webhooks', max_length=100, verbose_name='Webhook Token'),
        ),
    ]
