# Generated by Django 5.2.13 on 2026-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0008_expense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='pos_expense_sales_c_b099de_idx',
            old_name='pos_expense_sales_c_ed7a85_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='pos_expense_company_006e15_idx',
            old_name='pos_expense_company_3df88b_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
