# Generated by Django 5.2.13 on 2026-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0009_rename_pos_expense_sales_c_ed7a85_idx_pos_expense_sales_c_b099de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='wc_push_status_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, completing an order in the system (e.g. after packaging) pushes the mapped status (completed / cancelled / …) back to this WooCommerce store. A failed push never changes the local status — it is recorded for a retry.', verbose_name='Push order status to WooCommerce'),
        ),
    ]
