# Generated by Django 5.2.13 on 2026-06-07 00:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('sales_channels', '0010_saleschannel_wc_push_status_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('kind', models.CharField(choices=[('OPENING', 'Opening float / Fond de caisse'), ('TOP_UP', 'Cash added / Alimentation'), ('OTHER', 'Other / Autre')], default='TOP_UP', max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the cash went into the till.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_deposits', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_deposits_created', to=settings.AUTH_USER_MODEL)),
                ('sales_channel', models.ForeignKey(help_text='POS register the cash was added to.', on_delete=django.db.models.deletion.CASCADE, related_name='cash_deposits', to='sales_channels.saleschannel')),
            ],
            options={
                'db_table': 'pos_cash_deposit',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['sales_channel', 'occurred_at'], name='pos_cash_de_sales_c_aa89e4_idx'), models.Index(fields=['company', 'occurred_at'], name='pos_cash_de_company_bbbad9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='cash_deposit_amount_gt_zero')],
            },
        ),
    ]
