# Generated by Django 5.2.13 on 2026-06-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_channels', '0012_enable_wc_status_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_deposits_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
