# Generated by Django 5.2.15 on 2026-09-24 11:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_invoice_footer'),
        ('sales_channels', '0014_unify_cash_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('opening_cash', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('opening_cash_set', models.BooleanField(default=False, help_text='True after a cashier explicitly confirms the opening float.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField()),
                ('closing_cash_expected', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('closing_cash_actual', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('closing_note', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='company.company')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='sales_channels.saleschannel')),
            ],
            options={
                'db_table': 'pos_cash_session',
                'ordering': ['-business_date', '-id'],
                'indexes': [models.Index(fields=['company', 'business_date'], name='pos_cash_se_company_84f667_idx'), models.Index(fields=['sales_channel', 'status', 'business_date'], name='pos_cash_se_sales_c_5ee008_idx')],
                'constraints': [models.UniqueConstraint(fields=('sales_channel', 'business_date'), name='unique_cash_session_per_channel_day'), models.CheckConstraint(condition=models.Q(('opening_cash__gte', Decimal('0.000'))), name='cash_session_opening_non_negative')],
            },
        ),
    ]
