# Generated by Django 5.2 for LkSystem users app

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('brands', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this role (e.g., Admin, Manager, Employee)', max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of this role and its responsibilities', verbose_name='Description')),
                ('can_switch_brands', models.BooleanField(default=False, help_text='If True, user can switch between all allowed brands. If False, user is locked to their default/first brand only.', verbose_name='Can Switch Brands')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates this role as an admin role with elevated privileges', verbose_name='Is Admin Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions assigned to this role', related_name='custom_roles', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'users_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('matricule', models.CharField(help_text='Unique employee identifier (e.g., COMP-0001)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')], verbose_name='Matricule')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_brands', models.ManyToManyField(blank=True, help_text='Brands this user can access (must belong to current_company)', related_name='allowed_users', to='brands.brand', verbose_name='Allowed Brands')),
                ('current_company', models.ForeignKey(blank=True, help_text='The company this user belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.company', verbose_name='Company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Role determining permissions and access level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(blank=True, help_text='National Identity Card number', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CIN must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')], verbose_name='CIN Number')),
                ('cin_front', models.ImageField(blank=True, null=True, upload_to='profiles/cin/front/', verbose_name='CIN Front Image')),
                ('cin_back', models.ImageField(blank=True, null=True, upload_to='profiles/cin/back/', verbose_name='CIN Back Image')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport Number')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='profiles/passport/', verbose_name='Passport Image')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('nationality', models.CharField(blank=True, default='', max_length=100, verbose_name='Nationality')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number')),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Emergency Contact Name')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Profile Picture')),
                ('education_level', models.CharField(blank=True, choices=[('NONE', 'No Formal Education'), ('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('BAC', 'Baccalaureate'), ('LICENSE', 'License (Bachelor)'), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate (PhD)'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Education Level')),
                ('diploma_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Diploma/Degree Title')),
                ('diploma_file', models.FileField(blank=True, null=True, upload_to='profiles/diplomas/', verbose_name='Diploma File')),
                ('institution', models.CharField(blank=True, default='', max_length=200, verbose_name='Educational Institution')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('is_complete', models.BooleanField(default=False, help_text='Indicates if all required profile fields are filled', verbose_name='Profile Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_profile',
            },
        ),
    ]
