# Generated by Django 5.2.12 on 2026-03-23 23:19

import apps.users.models.invitation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('rbac', '0001_initial'),
        ('sales_channels', '0004_remove_saleschannel_woocommerce_config_and_more'),
        ('users', '0003_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Invited Email')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(default=apps.users.models.invitation.get_invitation_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, help_text='The User created when invitation was accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitation', to=settings.AUTH_USER_MODEL)),
                ('brands', models.ManyToManyField(blank=True, related_name='invitations', to='brands.brand', verbose_name='Assigned Brands')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='company.company', verbose_name='Company')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rbac.role', verbose_name='Assigned Role')),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='sales_channels.saleschannel', verbose_name='Assigned Sales Channel')),
            ],
            options={
                'db_table': 'users_invitation',
                'ordering': ['-created_at'],
            },
        ),
    ]
