# Generated by Django 5.2.13 on 2026-06-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_normalize_blank_cin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
