# Generated by Django 5.2.12 on 2026-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_company_f39d8e_idx',
            old_name='order_company_107b91_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_company_d2b176_idx',
            old_name='order_company_60cbda_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_sales_c_bdb745_idx',
            old_name='order_sales_c_332978_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_order_n_1515f9_idx',
            old_name='order_order_n_06f120_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, default='TN', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='TN', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='order',
            table='sales_order',
        ),
    ]
