# Generated by Django 5.2.13 on 2026-05-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_phone_normalized_type_birthdate'),
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('orders', '0013_order_not_answered_attempts'),
        ('products', '0010_product_categories'),
        ('sales_channels', '0009_rename_pos_expense_sales_c_ed7a85_idx_pos_expense_sales_c_b099de_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordersyncevent',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_wc_key_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_dlv_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_company_01fb2f_idx',
            old_name='sales_order_company_isdel_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_is_dele_ed5571_idx',
            old_name='sales_order_isdel_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_synced__5d0f69_idx',
            old_name='sales_order_synced_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_deliver_2a662b_idx',
            old_name='sales_order_dlv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_sales_c_1aa954_idx',
            old_name='sales_order_channel_wc_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='orderline',
            new_name='order_line_order_i_17f7a9_idx',
            old_name='order_line_order_isdel_idx',
        ),
        migrations.RenameIndex(
            model_name='orderline',
            new_name='order_line_is_dele_cc9a25_idx',
            old_name='order_line_isdel_idx',
        ),
        migrations.RenameIndex(
            model_name='orderlog',
            new_name='order_log_order_i_da5626_idx',
            old_name='order_log_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='orderlog',
            new_name='order_log_action_8cb1a4_idx',
            old_name='order_log_action_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersyncevent',
            new_name='order_sync__sales_c_acafaa_idx',
            old_name='order_sync_ch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersyncevent',
            new_name='order_sync__sales_c_c3f046_idx',
            old_name='order_sync_ch_started_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersyncevent',
            new_name='order_sync__company_b94bfc_idx',
            old_name='order_sync_co_started_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='auto_cancel_reason',
            field=models.CharField(blank=True, default='', help_text='Why the System auto-cancelled this order (e.g. not_answered_3d).', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='company.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External delivery provider reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_response',
            field=models.JSONField(blank=True, help_text='Last response from the delivery provider API', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('NONE', 'Not Applicable'), ('PENDING', 'Pending Submission'), ('QUEUED', 'Queued for Delivery'), ('SUBMITTED', 'Submitted to Provider'), ('ACCEPTED', 'Accepted by Provider'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed'), ('CANCELLED', 'Delivery Cancelled'), ('RETURNED', 'Returned to Sender')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, default='', help_text='WooCommerce numeric order ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_points_amount',
            field=models.PositiveIntegerField(default=0, help_text='Points granted (saved so we can reverse the exact amount on return/cancel).'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_points_granted',
            field=models.BooleanField(default=False, help_text='True once loyalty points have been credited to the client for this order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='not_answered_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When contact_status first became NOT_ANSWERED (drives auto-cancel scheduler).', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='raw_wc_payload',
            field=models.JSONField(blank=True, help_text='Raw JSON payload as received from WooCommerce REST API or webhook', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales_channels.saleschannel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('WOOCOMMERCE', 'WooCommerce'), ('POS', 'Point of Sale'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this order was successfully synced from WooCommerce', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw WooCommerce meta_data array, indexed by meta_key for fast lookup'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_order_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='WooCommerce order_key (wc_xxxx…) — secondary idempotency check', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='is_linked',
            field=models.BooleanField(default=True, help_text='False when a WC line could not be linked to a local Product. Unlinked lines never trigger stock movements.'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unlinked_reason',
            field=models.CharField(blank=True, default='', help_text='no_wc_id | no_sku | name_ambiguous | no_match', max_length=40),
        ),
        migrations.AlterField(
            model_name='ordersyncevent',
            name='sync_from',
            field=models.DateTimeField(blank=True, help_text='modified_after parameter sent to WooCommerce (NULL = full sync)', null=True),
        ),
        migrations.AlterField(
            model_name='ordersyncevent',
            name='wc_statuses_synced',
            field=models.JSONField(blank=True, default=list, help_text='List of WC statuses included, e.g. ["processing", "completed"]'),
        ),
    ]
