# Generated by Django 5.2.13 on 2026-05-29 01:24

import apps.orders.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('clients', '0005_client_phone_normalized_type_birthdate'),
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('orders', '0014_alter_orderline_options_alter_ordersyncevent_options_and_more'),
        ('sales_channels', '0009_rename_pos_expense_sales_c_ed7a85_idx_pos_expense_sales_c_b099de_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_high_min_amount', models.DecimalField(decimal_places=2, default=Decimal('299.00'), help_text='total >= this AND in_stock => HIGH priority.', max_digits=14)),
                ('priority_medium_min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='total >= this (and below high) => at least MEDIUM priority.', max_digits=14)),
                ('no_answer_max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Unanswered attempts before order_status becomes not_answered.')),
                ('pos_pickup_delivery_fee', models.DecimalField(decimal_places=3, default=Decimal('7.000'), help_text='Fee kept on POS-pickup orders at/above the waive threshold.', max_digits=8)),
                ('pos_pickup_fee_waive_below', models.DecimalField(decimal_places=2, default=Decimal('299.00'), help_text='POS-pickup orders below this have the delivery fee removed.', max_digits=14)),
                ('wc_status_map', models.JSONField(blank=True, default=apps.orders.models.default_wc_status_map, help_text='Maps local order_status values to WooCommerce status strings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'order_system_setting',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Confirmation agent assigned to this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('delayed', 'Delayed'), ('canceled', 'Canceled'), ('no_answer', 'No Answer')], default='pending', help_text='Confirmation-team result, separate from order_status.', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='delay_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delay_until',
            field=models.DateTimeField(blank=True, help_text='When to follow up on a delayed order.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('pos_pickup', 'POS Pickup')], default='home_delivery', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful push TO WooCommerce (distinct from synced_at, the last pull).', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('delayed', 'Delayed'), ('not_answered', 'Not Answered'), ('canceled', 'Canceled'), ('preparing', 'Preparing'), ('done', 'Done'), ('returned', 'Returned'), ('exchanged', 'Exchanged')], default='new', help_text='Clean business-lifecycle status (the single status the UI shows).', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Derived handling priority; recomputed by the service.', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('partial_stock', 'Partial Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', help_text='Derived per-order availability; recomputed by the service.', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_error_message',
            field=models.TextField(blank=True, default='', help_text='Last WooCommerce push error (set when sync_status=sync_failed).'),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('pending_sync', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed')], default='imported', help_text='State of pushing local changes TO WooCommerce.', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SOFT_DELETED', 'Soft Deleted'), ('RESTORED', 'Restored'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('STATUS_CHANGED', 'Status Changed'), ('WOOCOMMERCE_STATUS_CHANGED', 'WooCommerce Status Changed'), ('LOCAL_STATUS_CHANGED', 'Local Status Changed'), ('CONTACT_STATUS_CHANGED', 'Contact Status Changed'), ('DELAY_DATE_CHANGED', 'Delay Date Changed'), ('RETURN_EXCHANGE_CHANGED', 'Return / Exchange Changed'), ('EDIT_LOCK_ACQUIRED', 'Edit Lock Acquired'), ('EDIT_LOCK_RELEASED', 'Edit Lock Released'), ('EDIT_LOCK_TAKEN_OVER', 'Edit Lock Taken Over'), ('OUTCOME_CONFIRMED', 'Confirmed'), ('OUTCOME_DELAYED', 'Delayed'), ('OUTCOME_CANCELLED', 'Cancelled'), ('SYNC_RECEIVED', 'Synced from WooCommerce'), ('SYNC_FAILED', 'Sync Failed'), ('DELIVERY_QUEUED', 'Queued for Delivery'), ('DELIVERY_SUBMITTED', 'Submitted to Provider'), ('DELIVERY_ACCEPTED', 'Accepted by Provider'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_DELIVERED', 'Delivered'), ('DELIVERY_RETURNED', 'Returned to Sender'), ('SENT_TO_POS', 'Sent to POS'), ('POS_VALIDATED', 'POS Validated'), ('RETURN_PROCESSED', 'Return Processed'), ('STOCK_RESTORED', 'Stock Restored'), ('PACKAGED', 'Packaged'), ('PACKAGING_UPDATED', 'Packaging Updated'), ('PACKAGING_REVERSED', 'Packaging Reversed'), ('RETURN_TYPE_SET', 'Return Type Set'), ('FINAL_OUTCOME_CHANGED', 'Final Outcome Changed'), ('DAMAGED_STOCK_RECORDED', 'Damaged Stock Recorded'), ('REPLACEMENT_DEDUCTED', 'Replacement Product Deducted'), ('WORKFLOW_STATUS_CHANGED', 'Workflow Status Changed'), ('AUTO_CANCELLED', 'Auto Cancelled (System)'), ('POINTS_GRANTED', 'Loyalty Points Granted'), ('POINTS_REVERSED', 'Loyalty Points Reversed'), ('WC_PRODUCT_LINKED', 'WC Product Linked'), ('WC_PRODUCT_UNLINKED', 'WC Product Unlinked'), ('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('MANUAL_STATUS_OVERRIDE', 'Manual Status Override'), ('WC_CANCEL_SYNCED', 'WooCommerce Cancel Synced'), ('WC_SYNC_RETRIED', 'WooCommerce Sync Retried')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'order_status'], name='order_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'sync_status'], name='order_sync_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'priority_level'], name='order_priority_idx'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_setting', to='company.company'),
        ),
    ]
