# Generated by Django 5.2.13 on 2026-06-10 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('clients', '0006_client_matricule_fiscale'),
        ('company', '0004_company_invoice_footer'),
        ('orders', '0022_unified_status'),
        ('sales_channels', '0012_enable_wc_status_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_company_f39d8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_company_01fb2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_deliver_2a662b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='sales_order_outcome_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_lifecycle_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_contact_delay_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_return_exchange_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_final_outcome_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_packaging_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_workflow_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_not_answered_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_status_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmation_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_outcome',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packaging_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_exchange_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='workflow_status',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'is_deleted', '-created_at'], name='order_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'payment_status'], name='order_payment_status_idx'),
        ),
    ]
