# Generated by Django 5.2.13 on 2026-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailybrandchannelstats',
            new_name='bi_daily_br_company_ed3809_idx',
            old_name='bi_brand_ch_c_b_d_idx',
        ),
        migrations.RenameIndex(
            model_name='dailybrandchannelstats',
            new_name='bi_daily_br_company_e38b6a_idx',
            old_name='bi_brand_ch_full_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductresalestats',
            new_name='bi_daily_pr_company_6bc78d_idx',
            old_name='bi_resale_c_b_d_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductresalestats',
            new_name='bi_daily_pr_company_2b9a07_idx',
            old_name='bi_resale_full_idx',
        ),
        migrations.AlterField(
            model_name='dailybrandchannelstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailyproductresalestats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
