# Generated by Django 5.2.13 on 2026-06-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_invoice_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hidden_pages',
            field=models.JSONField(blank=True, default=list, help_text='Page keys this role cannot open (navigation only; does not change permissions).'),
        ),
    ]
