# Generated by Django 5.2.11 on 2026-02-28 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('sales_channels', '0003_add_store_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Billing e-mail (unique per company)', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='TN', max_length=5)),
                ('wc_customer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='WooCommerce Customer ID')),
                ('source', models.CharField(choices=[('WOOCOMMERCE', 'WooCommerce'), ('POS', 'Point of Sale'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant that owns this client record', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='sales_channels.saleschannel', verbose_name='Originating Channel')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'email'], name='client_company_597da1_idx'), models.Index(fields=['wc_customer_id'], name='client_wc_cust_b9e1a8_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
