# Generated by Django 5.2.12 on 2026-03-24 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('clients', '0001_initial'),
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('sales_channels', '0004_remove_saleschannel_woocommerce_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this client is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='brands.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Automatically set to True when returns exceed threshold', verbose_name='Blocked'),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Orders'),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_returns',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Returns'),
        ),
        migrations.AddField(
            model_name='client',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Loyalty Points'),
        ),
        migrations.AddField(
            model_name='client',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='Reseller who referred this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='clients.client', verbose_name='Reseller'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['brand'], name='client_brand_i_9eb375_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_blocked'], name='client_is_bloc_329548_idx'),
        ),
    ]
