# Generated by Django 5.2.13 on 2026-06-23 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_matricule_fiscale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Blocked At'),
        ),
        migrations.AddField(
            model_name='client',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='User who blocked the client manually; NULL for an automatic block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', help_text='Why the client is blocked (auto or manual). Empty when not blocked.', max_length=255, verbose_name='Block Reason'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Set automatically when returns reach the threshold, or manually.', verbose_name='Blocked'),
        ),
    ]
