# Generated by Django 5.2.11 on 2026-02-11 15:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('company', '0003_alter_company_abbreviation_alter_company_legal_name'),
        ('products', '0001_initial'),
        ('sales_channels', '0002_remove_config_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the promotion', max_length=255, verbose_name='Promotion Name')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the promotion', verbose_name='Description')),
                ('code', models.CharField(blank=True, default='', help_text='Optional coupon/promo code (e.g., SUMMER20)', max_length=50, verbose_name='Promotion Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Default Discount Type')),
                ('default_discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default discount (can be overridden per channel)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Default Discount Value')),
                ('start_date', models.DateTimeField(help_text='When the promotion becomes active', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='When the promotion expires', verbose_name='End Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch for this promotion', verbose_name='Is Active')),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promotion can be used (null = unlimited)', null=True, verbose_name='Maximum Usage')),
                ('current_usage', models.PositiveIntegerField(default=0, help_text='Number of times this promotion has been used', verbose_name='Current Usage')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority promotions are applied first (0 = lowest)', verbose_name='Priority')),
                ('is_stackable', models.BooleanField(default=False, help_text='Can this promotion be combined with others?', verbose_name='Is Stackable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Optional: Limit promotion to specific brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='brands.brand', verbose_name='Brand')),
                ('company', models.ForeignKey(help_text='Company that owns this promotion', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(help_text='The product this promotion applies to', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions_promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionChannelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Channel-specific discount (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount Value')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is this promotion active for this channel?', verbose_name='Enabled')),
                ('channel_priority', models.PositiveIntegerField(default=0, help_text='Priority for this channel (overrides promotion priority)', verbose_name='Channel Priority')),
                ('channel_max_usage', models.PositiveIntegerField(blank=True, help_text='Max usage for this specific channel (null = use promotion limit)', null=True, verbose_name='Channel Max Usage')),
                ('channel_current_usage', models.PositiveIntegerField(default=0, verbose_name='Channel Current Usage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rules', to='promotions.promotion', verbose_name='Promotion')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='sales_channels.saleschannel', verbose_name='Sales Channel')),
            ],
            options={
                'verbose_name': 'Promotion Channel Rule',
                'verbose_name_plural': 'Promotion Channel Rules',
                'db_table': 'promotions_channel_rule',
                'ordering': ['sales_channel__name'],
                'unique_together': {('promotion', 'sales_channel')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='sales_channels',
            field=models.ManyToManyField(help_text='Channels where this promotion is active (with specific discount rates)', related_name='promotions', through='promotions.PromotionChannelRule', to='sales_channels.saleschannel', verbose_name='Sales Channels'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'is_active'], name='promotions__status_d9349e_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_283aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['product'], name='promotions__product_f62e20_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['company'], name='promotions__company_73c939_idx'),
        ),
    ]
