# Generated by Django 5.2.11 on 2026-02-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
        ('sales_channels', '0002_remove_config_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotion',
            name='promotions__company_73c939_idx',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='company',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand for this promotion (linked to company via brand)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='brands.brand', verbose_name='Brand'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['brand'], name='promotions__brand_i_d69c81_idx'),
        ),
    ]
