# Generated by Django 5.2.12 on 2026-03-23 22:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_company_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionchannelrule',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Channel-specific discount (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Value'),
        ),
    ]
