# Generated by Django 5.2.13 on 2026-05-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_group_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotion',
            new_name='promotions__group_i_a0a5ac_idx',
            old_name='promotions__group_id_idx',
        ),
    ]
