# Generated by Django 5.2.11 on 2026-02-04 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_channels', '0002_remove_config_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_category_id', models.PositiveIntegerField(help_text='Unique identifier from WooCommerce', unique=True, verbose_name='WooCommerce Category ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the category name', max_length=255, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Category description from WooCommerce', verbose_name='Description')),
                ('wc_parent_id', models.PositiveIntegerField(blank=True, help_text='Parent category ID from WooCommerce (for sync resolution)', null=True, verbose_name='WooCommerce Parent ID')),
                ('image_url', models.URLField(blank=True, default='', help_text='Category image URL from WooCommerce', max_length=500, verbose_name='Image URL')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menu order from WooCommerce', verbose_name='Display Order')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last synchronization with WooCommerce', verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='Parent Category')),
                ('sales_channel', models.ForeignKey(help_text='The WooCommerce store this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sales_channels.saleschannel', verbose_name='Sales Channel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['wc_category_id'], name='category_wc_cate_b242da_idx'), models.Index(fields=['slug'], name='category_slug_4e15ec_idx'), models.Index(fields=['sales_channel', 'name'], name='category_sales_c_556788_idx')],
                'unique_together': {('sales_channel', 'wc_category_id')},
            },
        ),
    ]
