# Generated by Django 5.2.12 on 2026-03-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='wc_parent_id',
        ),
    ]
