# Generated by Django 5.2.12 on 2026-03-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_wc_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wc_category_id',
            field=models.PositiveIntegerField(help_text='Unique identifier from WooCommerce (unique per sales channel)', verbose_name='WooCommerce Category ID'),
        ),
    ]
