# Generated by Django 5.2.13 on 2026-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_wc_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded category image; its served URL is mirrored into image_url.', null=True, upload_to='categories/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Category image URL (from WooCommerce, or mirrored from an upload).', max_length=500, verbose_name='Image URL'),
        ),
    ]
