# Generated by Django 5.2.13 on 2026-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_image_alter_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wc_category_id',
            field=models.PositiveIntegerField(blank=True, help_text='Identifier from WooCommerce (unique per sales channel). NULL for categories created manually in-app.', null=True, verbose_name='WooCommerce Category ID'),
        ),
    ]
