# Generated by Django 5.2.11 on 2026-02-04 16:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('sales_channels', '0002_remove_config_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_product_id', models.PositiveIntegerField(help_text='Unique identifier from WooCommerce', verbose_name='WooCommerce Product ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the product name', max_length=255, verbose_name='URL Slug')),
                ('barcode', models.CharField(blank=True, default='', help_text='Stock Keeping Unit from WooCommerce', max_length=100, verbose_name='Barcode (SKU)')),
                ('description', models.TextField(blank=True, default='', help_text='Full product description', verbose_name='Description')),
                ('short_description', models.TextField(blank=True, default='', help_text='Brief product description for listings', verbose_name='Short Description')),
                ('product_type', models.CharField(choices=[('simple', 'Simple Product'), ('variable', 'Variable Product'), ('grouped', 'Grouped Product'), ('external', 'External/Affiliate Product')], default='simple', max_length=20, verbose_name='Product Type')),
                ('status', models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('private', 'Private')], default='publish', max_length=20, verbose_name='Publication Status')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for inventory/profit calculations', max_digits=12, verbose_name='Purchase Price')),
                ('sales_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular price from WooCommerce', max_digits=12, verbose_name='Sales Price (Regular)')),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price from WooCommerce (null if no promotion)', max_digits=12, null=True, verbose_name='Promotion Price (Sale)')),
                ('inventory_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20, verbose_name='Inventory Status')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Current stock level (null if not tracking)', null=True, verbose_name='Stock Quantity')),
                ('manage_stock', models.BooleanField(default=False, help_text='Whether stock is being tracked', verbose_name='Manage Stock')),
                ('image_url', models.URLField(blank=True, default='', help_text='Main product image URL from WooCommerce', max_length=500, verbose_name='Primary Image URL')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs', verbose_name='Gallery Images')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Product weight for shipping calculations', max_digits=10, null=True, verbose_name='Weight')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Product dimensions: {length, width, height}', verbose_name='Dimensions')),
                ('attributes', models.JSONField(blank=True, default=list, help_text='Product attributes from WooCommerce', verbose_name='Attributes')),
                ('wc_category_ids', models.JSONField(blank=True, default=list, help_text='WooCommerce category IDs (for sync resolution)', verbose_name='WC Category IDs')),
                ('permalink', models.URLField(blank=True, default='', help_text='Full URL to the product on WooCommerce', max_length=500, verbose_name='Permalink')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last synchronization with WooCommerce', verbose_name='Last Synced At')),
                ('wc_date_created', models.DateTimeField(blank=True, help_text='Original creation date in WooCommerce', null=True, verbose_name='WC Date Created')),
                ('wc_date_modified', models.DateTimeField(blank=True, help_text='Last modification date in WooCommerce', null=True, verbose_name='WC Date Modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Product brand (from local Brand model)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand', verbose_name='Brand')),
                ('categories', models.ManyToManyField(blank=True, help_text='Product categories', related_name='products', to='categories.category', verbose_name='Categories')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('sales_channel', models.ForeignKey(help_text='The WooCommerce store this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales_channels.saleschannel', verbose_name='Sales Channel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wc_product_id'], name='product_wc_prod_60b50b_idx'), models.Index(fields=['barcode'], name='product_barcode_d2887e_idx'), models.Index(fields=['slug'], name='product_slug_b8980b_idx'), models.Index(fields=['sales_channel', 'name'], name='product_sales_c_f75941_idx'), models.Index(fields=['inventory_status'], name='product_invento_5a11a7_idx'), models.Index(fields=['product_type'], name='product_product_f634b9_idx')],
                'unique_together': {('sales_channel', 'wc_product_id')},
            },
        ),
    ]
