# Generated by Django 5.2.12 on 2026-03-23 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='product',
            name='dim_height',
            field=models.CharField(blank=True, default='', help_text='Product height for shipping', max_length=20, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='dim_length',
            field=models.CharField(blank=True, default='', help_text='Product length for shipping', max_length=20, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='dim_width',
            field=models.CharField(blank=True, default='', help_text='Product width for shipping', max_length=20, verbose_name='Width'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Attribute Name')),
                ('value', models.TextField(blank=True, default='', verbose_name='Value')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible on product page')),
                ('is_variation', models.BooleanField(default=False, verbose_name='Used for variations')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'db_table': 'product_attribute',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_image',
                'ordering': ['position'],
                'unique_together': {('product', 'image_url')},
            },
        ),
    ]
