# Generated by Django 5.2.12 on 2026-03-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_attributes_remove_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wc_category_ids',
        ),
    ]
