# Generated by Django 5.2.12 on 2026-03-24 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0003_alter_category_wc_category_id'),
        ('products', '0003_remove_product_wc_category_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_sales_c_f75941_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'wc_product_id')},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple Product'), ('variable', 'Variable Product'), ('grouped', 'Grouped Product'), ('external', 'External/Affiliate Product'), ('resell', 'Resell Product'), ('packaging', 'Packaging / Emballage')], default='simple', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'name'], name='product_brand_i_45df63_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_channel',
        ),
    ]
