# Generated by Django 5.2.12 on 2026-03-25 00:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0004_remove_product_product_sales_c_f75941_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Soft Deleted'), ('restore', 'Restored')], max_length=10)),
                ('changes', models.JSONField(blank=True, help_text='JSON dict of changed fields: {field: [old, new]}', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'product_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_slug_b8980b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_invento_5a11a7_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dim_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dim_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dim_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manage_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotion_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, default='', help_text='External link to the product page', max_length=500, verbose_name='Product Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Barcode (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('resell', 'Resell Product'), ('packaging', 'Packaging / Emballage')], default='resell', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('private', 'Private')], default='publish', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wc_date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WC Date Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wc_date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WC Date Modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wc_product_id',
            field=models.PositiveIntegerField(default=0, help_text='Unique identifier from WooCommerce (0 for local-only products)', verbose_name='WooCommerce Product ID'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted', 'created_at'], name='product_is_dele_09c35a_idx'),
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product'),
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
