# Generated by Django 5.2.13 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_category_wc_category_id"),
        ("products", "0009_product_image_url_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Product categories synchronized from WooCommerce",
                related_name="products",
                to="categories.category",
                verbose_name="Categories",
            ),
        ),
    ]
